name: Test Objectstorage

on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *'

env:
  DOCKERHUB_ORG: ${{ secrets.DOCKERHUB_ORG }}

jobs:
  test_objectstorage:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        server: ["https://object-store.rc.nectar.org.au/v1/AUTH_dead991e1fa847e3afcca2d3a7041f5d/neurodesk/"]
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - name: check if ${{ matrix.server }} is online and up-to-date
      run: /bin/bash .github/workflows/test_objectstorage.sh  ${{ matrix.server }}
