name: Test cvmfs

permissions:
  contents: read
  pull-requests: write

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 17 * * *'
    
env:
  DOCKERHUB_ORG: ${{ secrets.DOCKERHUB_ORG }}

jobs:
  test_cvmfs_1_2_3:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - name: check if cvmfs setup with multiple entries works
      run: /bin/bash .github/workflows/test_cvmfs_1_2_3.sh
    - name: Generate issue on job failure
      if: always() && failure()
      uses: JasonEtco/create-an-issue@1b14a70e4d8dc185e5cc76d3bec9eab20257b2c5
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_WORKFLOW: ${{ env.GITHUB_WORKFLOW }}
        GITHUB_SERVER_URL: ${{ env.GITHUB_SERVER_URL }}
        GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
        GITHUB_RUN_ID: ${{ env.GITHUB_RUN_ID }}
      with:
        filename: .github/job_failure_issue_template.md
        update_existing: true
        search_existing: open
  test_cvmfs:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        cvmfs-servers: ["s1fnal-cvmfs.openhtc.io:8080",
                        "s1sampa-cvmfs.openhtc.io:8080",
                        "s1bnl-cvmfs.openhtc.io",
                        "s1osggoc-cvmfs.openhtc.io:8080",
                        "s1brisbane-cvmfs.openhtc.io",
                        "s1sydney-cvmfs.openhtc.io",
                        "s1melbourne-cvmfs.openhtc.io",
                        "s1perth-cvmfs.openhtc.io",
                        "cvmfs-frankfurt.neurodesk.org",
                        "cvmfs-jetstream.neurodesk.org",
                        "s1ral-cvmfs.openhtc.io",
                        "cvmfs-geoproximity.neurodesk.org"]

                        # "cvmfs-s1.hpc.swin.edu.au",
                        # "cvmfs-stratum-one.ihep.ac.cn",
                        # "s1nikhef-cvmfs.openhtc.io"
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - name: check if ${{ matrix.cvmfs-servers }} is online and up-to-date
      run: /bin/bash .github/workflows/test_cvmfs.sh  ${{ matrix.cvmfs-servers }}
    - name: Generate issue on job failure
      if: always() && failure()
      uses: JasonEtco/create-an-issue@1b14a70e4d8dc185e5cc76d3bec9eab20257b2c5
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_WORKFLOW: ${{ env.GITHUB_WORKFLOW }}
        GITHUB_SERVER_URL: ${{ env.GITHUB_SERVER_URL }}
        GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
        GITHUB_RUN_ID: ${{ env.GITHUB_RUN_ID }}
      with:
        filename: .github/job_failure_issue_template.md
        update_existing: true
        search_existing: open
